# file-path: /.github/workflows/slack-alarm-webhook.yml

name: "슬랙 웹훅 테스c1"

on:
  pull_request:
    types: [opened] # PR 등록시, slack에 자동 알림
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  mention_notification:
    name: Mention Notification
    runs-on: ubuntu-latest
    steps:
      - uses: Laurenfrost/mention-to-slack@latest
        with:
          configuration-path: .github/mention-to-slack.yml
          repo-token: ${{ secrets.GH_TOKEN }}
          slack-webhook-url: ${{ secrets.DABIN_TEST1 }}